---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ephemeral-environment-controller
data:
  # Patch this ConfigMap with additional values needed for your cloud
  KUBE_SECRET: flux-system # does not yet exist -- will be created in the same Namespace
  SSH_KEY_NAME: identity
  SYNC_PERIOD: "3600"  # tokens expire; refresh faster than that
  GIT_REPO: git@github.com:alam0rt/dotfiles.git
  GIT_BRANCH: main
  GIT_SSH_COMMAND: ssh -i /app/ssh_keys/${SSH_KEY_NAME:-id_rsa} -F /dev/null

---
# This Deployment frequently fetches registry tokens and applies them as an imagePullSecret.
# It's done as a 1-replica Deployment rather than a CronJob, because CronJob scheduling can
# block cluster bootstraps and cGIT_SSH_COMMANDold-reboots from obtaining registry tokens for a considerable time.
# This deployment will immediately fetch a token, which reduces latency for working image updates.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-environment-controller
  namespace: flux-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccount: ephemeral-environment-controller
      containers:
      - image: busybox  # override this with a cloud-specific image
        name: controller
        envFrom:
        - configMapRef:
            name: ephemeral-environment-controller
        env:
        - name: RECONCILE_SH  # override this env var with a shell function in a kustomize patch
          value: |-
            reconcile() {
              echo reconciling...
              workdir
              get-git-repos
            }
        command:
        - bash
        - -ceu
        - |-
          # template reconcile() into the script
          # env var is expanded by k8s before the pod starts
          $(RECONCILE_SH)

          workdir() {
              cd /app/clonedir
          }

          get-git-repos() {
              git clone ${GIT_REPO} --branch ${GIT_BRANCH} --single-branch 
          }

          pause_loop() {
            sleep "${SYNC_PERIOD:-3600}" || true
          }

          graceful_exit() {
            echo "Trapped signal -- $(date)"
            job_ids="$(
              jobs \
                | grep "pause_loop" \
                | cut -d] -f1 \
                | tr [ %
              )"
            # shellcheck disable=SC2086
            if [ "${job_ids}" ]; then
              kill ${job_ids}
            fi
            wait
            echo "Graceful exit -- $(date)"
          }

          trap graceful_exit INT TERM

          echo "Loop started (period: ${SYNC_PERIOD} s) -- $(date)"
          while true; do
            reconcile & wait $!
            pause_loop & wait $!
          done
        resources: {}
        volumeMounts:
          - mountPath: /app/ssh_keys
            name: keys
          - mountPath: /app/clonedir
            name: clonedir
      volumes:
        - name: keys
          secret:
            secretName: $(KUBE_SECRET)
            defaultMode: 0400
        - name: clonedir
          emptyDir: {}



# RBAC necessary for our Deployment to apply our imagePullSecret
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ephemeral-environment-controller
  namespace: flux-system
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  resourceNames:
  - $(KUBE_SECRET)  # templated from kustomize vars referencing ConfigMap, also see kustomizeconfig.yaml
- apiGroups: ["kustomize.toolkit.fluxcd.io"]
  resources:
    - kustomizations
  verbs:
    - get
    - create
    - update
    - patch
    - delete
    - list
- apiGroups: ["source.toolkit.fluxcd.io"]
  resources:
    - gitrepositories
  verbs:
    - get
    - create
    - update
    - patch
    - delete
    - list
  # # Lock this down to the specific Secret name  (Optional)
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ephemeral-environment-controller
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: ephemeral-environment-controller
roleRef:
  kind: Role
  name: ephemeral-environment-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ephemeral-environment-controller
  namespace: flux-system